In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier

%matplotlib inline

In [2]:
np.array([1, 2])

np.matrix([1, 2])

np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
m = np.matrix([[1.5, 2, 3], [4, 5, 6]], dtype=int)

m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [4]:
m.shape

(2, 3)

In [21]:
m = m.flatten().tolist()[0]

In [6]:
m.reshape(3, 2)

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
np.std(m)

1.707825127659933

In [30]:
np.std(m + [1])

1.8070158058105024

In [ ]:
nn = MLPClassifier(hidden_layer_sizes=(100, 100))

In [40]:
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(
    xlabel='Eixo X',
    ylabel='Eixo Y',
    title='Meu x gráfico'
)

ax.grid()
plt.show()